name: Test find_lowest_number.py

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with 10 numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
    - name: Test with 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
    - name: Test with an empty file
      run: |
        python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
